---
title: Introduction to Parallel Computing and Machine Learning with pbdR
site: sandpaper::sandpaper_site
---

The lessons below were designed for those interested
in using R for big data analysis and machine learning. 

This introduction assumes some prior programming experience
for example from one of the Carpentries R or Python lessons. Additionally,
some experience with the command line from one of the Carpentries
Unix shell lessons would be beneficial, but is not strictly required.

This lesson assumes no prior knowledge of R or RStudio.

## Episodes

1. [Before we start](00-before-we-start.html)
2. [Introduction: What is Parallel and Big Data Computing?](01-intro.html)
3. [Running a Shared Memory Parallel R Job on a Cluster](02-submit-job.html)
4. [Using R for multicore Random Forest](03-multicore.html)
5. [Multicore matrix multiplication with BLAS](04-blas.html)
6. [The Message Passing Interface](05-mpi.html)
7. [pbdMPI](06-pbdmpi.html)
8. [Random Forest with MPI](07-random-forest-mpi.html)
9. [Randomized Parallel SVD](08-randomized-parallel-svd.html)
10. [Conclusion](09-conclusion.html)

## Preparations

Carpentry's teaching is hands-on, and to follow this lesson
learners must have a linux shell environment, R and RStudio installed
on their computers. They also need to be able to install a number of R
packages, create directories, and download files.

To avoid troubleshooting during the lesson, learners should follow the
instructions below to download and install everything beforehand.
If they are using their own computers this should be no problem,
but if the computer is managed by their organization's IT department
they might need help from an IT administrator.

## Acknowledgments

This lesson draws material from

- [R for HPC](https://github.com/RBigData/R4HPC)

- [R Ecology lesson](https://datacarpentry.org/R-ecology-lesson/)

- [R Social Science lesson](https://datacarpentry.org/r-socialsci)

- [Unix Shell lesson](https://swcarpentry.github.io/shell-novice/)  
